# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0065_auto_20171216_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
